import { ArrowUpRight, MapPin, Phone, Mail, Instagram, Facebook } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import PageIntro from "@/components/PageIntro";
import { PlaceImage } from "@/components/PlaceImage";
import { mapUrl } from "@/components/SiteLayout";
export default function Contact() {
  return <><PageIntro title="Contact & accès" eyebrow="Rendez-vous au bord du lac"><p>La Buvette de l’Oued vous donne rendez-vous à la plage de Préverenges, face au lac et aux Alpes.</p></PageIntro>
    <section className="page-width grid items-center gap-10 py-14 md:grid-cols-2 lg:gap-20 lg:py-20"><div><MapPin size={30} className="text-primary" /><h2 className="section-title mt-5">Nous trouver</h2><address className="mt-6 text-lg not-italic leading-8">Buvette de l’Oued<br />Av. de la Plage 27<br />1028 Préverenges</address><p className="mt-3 text-xs text-muted-foreground">Adresse reprise du site actuel. Actualité : [À confirmer].</p><Button asChild className="mt-7 h-12 rounded-full px-6"><a href={mapUrl} target="_blank" rel="noreferrer">Ouvrir l’itinéraire <ArrowUpRight className="ml-2 h-4 w-4" /><span className="sr-only"> (Google Maps, nouvel onglet)</span></a></Button><p className="mt-4 text-xs leading-6 text-muted-foreground">L’itinéraire s’ouvre sur Google Maps. Aucune carte externe n’est chargée sur cette page.</p></div><div className="aspect-[5/4] overflow-hidden rounded-3xl"><PlaceImage /></div></section>
    <section className="bg-secondary/55"><div className="page-width grid gap-12 py-14 md:grid-cols-2 lg:gap-20"><div><p className="eyebrow">Gardons le contact</p><h2 className="mt-4 text-2xl font-semibold text-primary">Contacter la buvette</h2><dl className="mt-7 space-y-6"><div className="flex gap-4"><Phone size={21} className="mt-1 text-primary" /><div><dt className="font-semibold">Téléphone</dt><dd className="mt-1 text-sm text-muted-foreground">[À confirmer]</dd></div></div><div className="flex gap-4"><Mail size={21} className="mt-1 text-primary" /><div><dt className="font-semibold">E-mail</dt><dd className="mt-1 text-sm text-muted-foreground">[À confirmer]</dd></div></div></dl><p className="mt-7 text-sm text-muted-foreground">Possibilité et modalités de réservation : [À confirmer]</p></div><div><p className="eyebrow">La vie au bord de l’eau</p><h2 className="mt-4 text-2xl font-semibold text-primary">Suivre l’Oued</h2><p className="body-copy mt-5">Les soirées à thème et événements sont annoncés sur les réseaux sociaux.</p><div className="mt-6 space-y-4 text-sm"><p className="flex items-center gap-3"><Instagram size={20} className="text-primary" />Instagram · lien officiel [À confirmer]</p><p className="flex items-center gap-3"><Facebook size={20} className="text-primary" />Facebook · lien officiel [À confirmer]</p></div></div></div></section>
    <section className="page-width py-14"><h2 className="text-2xl font-semibold text-primary">Préparer votre visite</h2><div className="mt-6 grid gap-8 sm:grid-cols-2"><div><h3 className="font-semibold">Horaires & météo</h3><p className="body-copy mt-2">L’ouverture varie selon la période et les conditions météorologiques.</p><Link to="/horaires" className="text-link mt-4">Consulter les horaires</Link></div><div><h3 className="font-semibold">Accès pratique</h3><p className="body-copy mt-2">Stationnement, transports publics et accessibilité : [À confirmer]</p></div></div></section>
  </>;
}
