import { ArrowUpRight, Phone, Mail, Instagram, Facebook } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import PageIntro from "@/components/PageIntro";
import { mapUrl } from "@/components/SiteLayout";

export default function Contact() {
  return <><PageIntro title="Contact & accès" eyebrow="On se retrouve à la plage ?"><p>Direction Préverenges, les parasols et le lac. Toutes les informations pour venir à l’Oued.</p></PageIntro>
    <div className="page-width py-12 sm:py-16"><div className="grid gap-12 md:grid-cols-2 lg:gap-24">
      <section><p className="eyebrow">Les pieds presque dans l’eau</p><h2 className="mt-4 text-2xl font-semibold text-primary">Nous trouver</h2><address className="mt-5 text-lg not-italic leading-8">Buvette de l’Oued<br />Av. de la Plage 27<br />1028 Préverenges</address><Button asChild className="mt-6 h-12 rounded-full px-6"><a href={mapUrl} target="_blank" rel="noreferrer">Voir l’itinéraire <ArrowUpRight className="ml-2 h-4 w-4" /><span className="sr-only"> (Google Maps, nouvel onglet)</span></a></Button><p className="mt-4 text-xs leading-6 text-muted-foreground">Actualité de l’adresse : [À confirmer].<br />Stationnement, transports et accessibilité : [À confirmer].</p><Link to="/horaires" className="text-link mt-5">Consulter les horaires avant de venir</Link></section>
      <section><p className="eyebrow">Un mot, une question</p><h2 className="mt-4 text-2xl font-semibold text-primary">Gardons le contact</h2><dl className="mt-6 space-y-5 text-sm"><div className="flex items-start gap-3"><Phone size={18} className="mt-0.5 shrink-0 text-primary" /><div><dt className="font-medium">Téléphone</dt><dd className="mt-1 text-muted-foreground">[À confirmer]</dd></div></div><div className="flex items-start gap-3"><Mail size={18} className="mt-0.5 shrink-0 text-primary" /><div><dt className="font-medium">E-mail</dt><dd className="mt-1 text-muted-foreground">[À confirmer]</dd></div></div></dl><p className="mt-6 text-sm leading-7 text-muted-foreground"><span className="font-medium text-foreground">Réservations</span><br />Possibilité et modalités : [À confirmer]</p></section>
    </div><section className="mt-14 border-t border-primary/15 pt-9"><div className="grid gap-6 md:grid-cols-2 lg:gap-24"><div><h2 className="text-2xl font-semibold text-primary">La vie de la buvette</h2><p className="body-copy mt-3">Soirées à thème et événements : les rendez-vous sont annoncés sur nos réseaux sociaux.</p></div><div className="space-y-4 text-sm leading-6 text-muted-foreground"><p className="flex items-start gap-3"><Instagram size={20} className="mt-0.5 shrink-0 text-primary" /><span>Instagram · lien officiel [À confirmer]</span></p><p className="flex items-start gap-3"><Facebook size={20} className="mt-0.5 shrink-0 text-primary" /><span>Facebook · lien officiel [À confirmer]</span></p></div></div></section></div>
  </>;
}
